version: 2

updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 30
    groups:
      biome:
            patterns:
              - '@biomejs*'
      react:
        patterns:
          - 'react*'
      types:
        patterns:
          - '@types/*'

      ui:
        patterns:
          - '@fortawesome/*'
      utils:
        patterns:
          - '@w3ux/*'
          - 'date-fns'
          - 'buffer'
          - 'rxjs'
      polkadot:
        patterns:
          - '@polkadot/*'
          - 'dedot'
          - '@dedot/*'
    commit-message:
      prefix: 'deps'

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
