/* @license Copyright 2024 @polkadot-cloud/library authors & contributors
SPDX-License-Identifier: GPL-3.0-only */

import { ExtensionConfig, HardwareConfig } from "./types";

export const Extensions: Record<string, ExtensionConfig> = {
  enkrypt: {
    title: "Enkrypt",
    website: "enkrypt.com",
    features: "*",
  },
  "fearless-wallet": {
    title: "Fearless Wallet",
    website: "fearlesswallet.io",
    features: "*",
  },
  "metamask-polkadot-snap": {
    title: "MetaMask Polkadot Snap",
    website: [
      "snaps.metamask.io",
      "snaps.metamask.io/snap/npm/chainsafe/polkadot-snap",
    ],
    features: ["getAccounts", "signer"],
  },
  polkagate: {
    title: "PolkaGate",
    website: "polkagate.xyz",
    features: "*",
  },
  "subwallet-js": {
    title: "SubWallet",
    website: "subwallet.app",
    features: "*",
  },
  talisman: {
    title: "Talisman",
    website: "talisman.xyz",
    features: "*",
  },
  // NOTE: Nova Wallet use the same identifier as Polkadot JS extension. We therefore test if the
  // `walletExtension` property exists to determine if the extension is Nova Wallet or Polkadot JS.
  "polkadot-js": {
    title: window?.walletExtension?.isNovaWallet
      ? "Nova Wallet"
      : "Polkadot JS",
    website: window?.walletExtension?.isNovaWallet
      ? "novawallet.io"
      : "polkadot.js.org/extension",
    features: "*",
  },
};

export const Hardware: Record<string, HardwareConfig> = {
  ledger: {
    title: "Ledger",
    website: "ledger.com",
  },
  polkadotvault: {
    title: "Polkadot Vault",
    website: "signer.parity.io/",
  },
  walletconnect: {
    title: "WalletConnect",
    website: "walletconnect.com",
  },
};

// TODO: Code from here should be generated by build process.

// Format lists as arrays.
// ----------------------------------

// export const ExtensionsArray = Object.entries(Extensions).map(
//   ([key, value]) => ({
//     id: key,
//     ...value,
//   })
// );

// export const HardwareArray = Object.entries(Hardware).map(([key, value]) => ({
//   id: key,
//   ...value,
// }));

// export const ExtensionIcons: ExtensionIconRecords = {
//   enkrypt: Enkrypt,
//   "fearless-wallet": FearlessWallet,
//   "metamask-polkadot-snap": MetaMask,
//   novawallet: NovaWallet,
//   "polkadot-js": PolkadotJS,
//   polkagate: PolkaGate,
//   "subwallet-js": SubwalletJS,
//   talisman: Talisman,
// };

// export const HardwareIcons: ExtensionIconRecords = {
//   ledger: Ledger,
//   polkadotvault: PolkadotVault,
//   walletconnect: WalletConnect,
// };
